-- CreateTable
CREATE TABLE "Puzzle" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "scheduledFor" TIMESTAMP(3) NOT NULL,
    "image" STRING NOT NULL,
    "solveCount" INT4 NOT NULL DEFAULT 0,
    "attempCount" INT4 NOT NULL DEFAULT 0,

    CONSTRAINT "Puzzle_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Hitbox" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "puzzleId" INT4 NOT NULL,
    "topLeftX" INT4 NOT NULL,
    "topLeftY" INT4 NOT NULL,
    "bottomRightX" INT4 NOT NULL,
    "bottomRightY" INT4 NOT NULL,

    CONSTRAINT "Hitbox_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Hitbox" ADD CONSTRAINT "Hitbox_puzzleId_fkey" FOREIGN KEY ("puzzleId") REFERENCES "Puzzle"("id") ON DELETE CASCADE ON UPDATE CASCADE;
